### ISSUE TITLE
[Feature request] More architectures

### ISSUE THREAD

**Issue by joxeankoret** [c01db33f/reil#2]
Hi,

Are you going to add support for more architectures? Like translating MIPS, SH4 or ARM to REIL?

Thanks!

**Comment by c01db33f** [comment]
Unlikely that I will ever want to support SH4; not sure about MIPS.

I would like to implement ARM support at some point; but high-quality
x86-64 is more of a priority; and I'm not working on this exactly all the
time at the moment, so it's unlikely I'll be implementing further
architectures in the next 6 months.

Regards,
c01db33f

**Comment by joxeankoret** [comment]
OK, thanks for the info!
